# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40f1a1a1c4d67f0a608d129707d9bc5cbd3ee2f6086c2674b8e00e5bb54e6b47bc20c52ffeeb7ae1afacff9e5676cc465522b20b8f8ae5e73add729c9889a22f

test:
  secret_key_base: 77c49dbfbec136f9108155019c4dd680d3f3bb62f5e9714e4cc5d27740ea75b75841116cac62e6ffc34790d862f4b5b86171e063cc7ceae6514be312c9339d89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
